image: node:12.6

cache:
  paths:
    - node_modules/

before_script:
  - npm i

stages:
  - test
  - build

test_unit:
  stage: test
  script:
    - npm run test

test_e2e:
  stage: test
  variables:
    CI_DEBUG_TRACE: "true"
  script:
    - npm run test:e2e

build:
  stage: build
  script:
    - npm run build
