image: node:12.6

cache:
  paths:
    - node_modules/

stages:
    - test
    - build

test_unit:
    stage: test
    script:
        - npm run test

test_e2e:
    stage: test
    script:
        - npm run e2e

build:
    stage: build
    script:
        - npm run build
