services:
  - name: mongo:4.4.0
    alias: mongodb

variables:
  MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
  MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWD

image: node:12.6

cache:
  paths:
    - node_modules/

before_script:
  - npm i

stages:
  - test
  - build

test_unit:
  stage: test
  script:
    - npm run test:cov -- --forceExit

test_e2e:
  stage: test
  script:
    - npm run test:e2e -- --forceExit

build:
  stage: build
  script:
    - npm run build
