export enum ErrorType {
  BUSINESS_RULE = 'BUSINESSS_RULE',
  MISSING_MANDATORY_PARAMETER = 'MISSING_MANDATORY_PARAMETER',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  PERSISTENCE_ERROR = 'PERSISTENCE_ERROR',
}
